# Workflow untuk melakukan CI pipeline untuk dua branch: karsajobs (backend) dan karsajobs-ui (frontend)
name: CI Pipeline

# Workflow ini berjalan hanya pada branch tertentu saat terjadi push
on:
  push:
    branches:
      - karsajobs
      - karsajobs-ui
  workflow_dispatch:

# Menentukan environment yang digunakan (ubuntu-latest VM dari GitHub)
jobs:
  build:
    runs-on: ubuntu-latest

    # Menentukan matrix job untuk dua branch yang berbeda
    strategy:
      matrix:
        branch: [karsajobs, karsajobs-ui]

    # Langkah-langkah yang dijalankan di setiap job
    steps:
      # Step 1: Checkout kode dari branch yang sedang berjalan
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker untuk kebutuhan build & push image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login ke GitHub Container Registry (ghcr.io)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Lint Dockerfile menggunakan Hadolint
      - name: Lint Dockerfile with Hadolint
        run: |
          curl -LO https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          if [[ "${GITHUB_REF##*/}" == "karsajobs" ]]; then
            ./hadolint-Linux-x86_64 karsajobs/Dockerfile
          elif [[ "${GITHUB_REF##*/}" == "karsajobs-ui" ]]; then
            ./hadolint-Linux-x86_64 karsajobs-ui/Dockerfile
          fi

      # Step 5 (Opsional): Unit test hanya dijalankan jika branch == karsajobs (backend)
      - name: Run Go unit tests
        if: matrix.branch == 'karsajobs'
        run: |
          if [[ "${GITHUB_REF##*/}" == "karsajobs" ]]; then
            go test -v -short --count=1 $(go list karsajobs/...)
          fi

      # Step 6: Build dan Push image ke GHCR
            # Step 6: Build dan Push Docker Image
      - name: Build and Push Image
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${GITHUB_REF##*/}"

          if [[ "$BRANCH" == "karsajobs" ]]; then
            IMAGE_NAME="karsajobs"
            DOCKER_PATH="karsajobs"

            TAG="latest"
            FULL_IMAGE="ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:$TAG"

            echo "🚀 Membuat Docker image..."
            docker build -t $IMAGE_NAME:$TAG $DOCKER_PATH

            echo "📜 Daftar image lokal:"
            docker images

            echo "🔄 Menyesuaikan nama image untuk GitHub Packages..."
            docker tag $IMAGE_NAME:$TAG $FULL_IMAGE

            echo "🔑 Login ke GitHub Packages..."
            echo "$GITHUB_PAT" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin

            echo "☁️ Mengunggah image ke GitHub Packages..."
            docker push $FULL_IMAGE

            echo "✅ Selesai! Image berhasil diunggah ke GHCR: $FULL_IMAGE"
          elif [[ "$BRANCH" == "karsajobs-ui" ]]; then
            IMAGE_NAME="karsajobs-ui"
            DOCKER_PATH="karsajobs-ui"

            TAG="latest"
            FULL_IMAGE="ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:$TAG"

            echo "🚀 Membuat Docker image..."
            docker build -t $IMAGE_NAME:$TAG $DOCKER_PATH

            echo "📜 Daftar image lokal:"
            docker images

            echo "🔄 Menyesuaikan nama image untuk GitHub Packages..."
            docker tag $IMAGE_NAME:$TAG $FULL_IMAGE

            echo "🔑 Login ke GitHub Packages..."
            echo "$GITHUB_PAT" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin

            echo "☁️ Mengunggah image ke GitHub Packages..."
            docker push $FULL_IMAGE

            echo "✅ Selesai! Image berhasil diunggah ke GHCR: $FULL_IMAGE"
          fi
